[workspace]
resolver = "1"
members = ["cmds", "crates/cores", "crates/server", "crates/views", "tests"]

[workspace.dependencies]
axum = { version = "0.7", features = ["macros", "multipart"] }
tower-http = { version = "0.6", features = ["cors"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "process"] }
tauri = { version = "1", features = ["http-all", "system-tray", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22.1"
mio = "1.0.1"
thiserror = "1.0.63"
aes = "0.7"
block-modes = "0.8"
block-padding = "0.2"
chrono = "0.4"
aes-gcm = "0.10.3"
rand = "0.8.5"
winapi = { version = "0.3", features = ["dpapi", "winerror"] }
rusqlite = { version = "0.26", features = ["bundled"] }
lazy_static = "1.5.0"
config = "0.14"
tracing = "0.1"
tracing-subscriber = "0.3"

# internal crate dependencies
cores = { path = "./crates/cores" }
server = { path = "./crates/server" }
