[app]
id = "com.fantasy-browser.browser"
name = "fantasy-browser"
remote_switch = false
# remote_url = 'http://119.28.117.240:5678/'
remote_url = 'http://192.168.6.122:5678/'

[app.location]
user_data_location = "user-data"
user_logs_location = "user-logs"
browser_drivers_location = "browser-drivers"
browser_extensions_location = "browser-extensions"

[database]
driver = "sqlite3"
url = "fantasy-browser.db"
location = "cache"

[email]
smtp_username = "liushuinew@163.com"
smtp_password = "NSgjTyY6uSQwPGwV"
smtp_server = "smtp.163.com"