[app]
id = "com.ads-hubstudio.browser"
name = "ads-hubstudio"
remote_switch = false
remote_url = 'http://192.168.6.116:8080'

[app.location]
user_data_location = "user-data"
user_logs_location = "user-logs"
browser_drivers_location = "browser-drivers"
browser_extensions_location = "browser-extensions"

[database]
driver = "sqlite3"
url = "ads-hubstudio.db"
location = "cache"
