[app]
id = "com.ads-hubstudio.browser"
name = "ads-hubstudio"
remote_switch = false

[app.location]
user_data_location = "datas/user-data"
user_logs_location = "datas/user-logs"
browser_drivers_location = "datas/browser-drivers"
browser_extensions_location = "datas/browser-extensions"

[database]
driver = "sqlite3"
url = "ads-hubstudio.db"
location = "cache"
