[app]
id = "com.ads-hubstudio.browser"
name = "ads-hubstudio"

[cache]
# name = "ads-hubstudio.db"
name = "sqlite::memory"
location = "cache"
migrate_location = "migrations"

[log]
path = "logs"

[setting]
data_location = "datas"
user_data_location = "user_data"
user_proxy_location = "user_proxy"
all_locations = ["user_data", "user_proxy"]
