[package]
name = "lp_models"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }

lp_commons = { workspace = true }
lp_states = { workspace = true }
