export { default as IconAutomation } from './automation.svg'
export { default as IconAutomationActive } from './automation-active.svg'
export { default as IconDownloads } from './downloads.svg'
export { default as IconEnvironmentListActive } from './environment-list-active.svg'
export { default as IconEnvironmentList } from './environment-list.svg'
export { default as IconEnvironmentAppend } from './environment-append.svg'
export { default as IconEnvironmentAppend1 } from './environment-append-1.svg'
export { default as IconGroupActive } from './group-active.svg'
export { default as IconGroup } from './group.svg'
export { default as IconLogActive } from './log-active.svg'
export { default as IconLog } from './log.svg'
export { default as IconMessage } from './message.svg'
export { default as IconProxyActive } from './proxy-active.svg'
export { default as IconProxy } from './proxy.svg'
export { default as IconSoftwareActive } from './software-active.svg'
export { default as IconSoftware } from './software.svg'
export { default as IconTeamActive } from './team-active.svg'
export { default as IconTeam } from './team.svg'
export { default as IconTransferActive } from './transfer-active.svg'
export { default as IconTransfer } from './transfer.svg'
export { default as IconTransform } from './transform.svg'
export { default as IconTrashActive } from './trash-active.svg'
export { default as IconTrash } from './trash.svg'
export { default as IconUpdate } from './update.svg'
export { default as IconAccountActive } from './account-active.svg'
export { default as IconAccount } from './account.svg'
export { default as IconWindowSyncActive } from './window-sync-active.svg'
export { default as IconWindowSync } from './window-sync.svg'
export { default as IconChevronDown } from './chevron-down.svg'
export { default as IconLogo } from './logo.svg'
export { default as IconAnyMember } from './anyone-member.svg'
export { default as IconAnyMemberActive } from './anyone-member-active.svg'
export { default as IconBlock } from './block.svg'
export { default as IconBlockActive } from './block-active.svg'
export { default as IconGroupManagement } from './group-management.svg'
export { default as IconGroupManagementActive } from './group-management-active.svg'
export { default as IconMembershipApplication } from './membership-application.svg'
export { default as IconMembershipApplicationActive } from './membership-application-active.svg'
export { default as IconRpa } from './rpa.svg'
export { default as IconApi } from './api.svg'
export { default as IconApiActive } from './api-active.svg'
export { default as IconTeamGroupRefresh } from "./teamGroupRefresh.svg"
export { default as IconApiTxt } from "./api-txt.svg"
export { default as IconLinuxOs } from "./linux-os.svg"
export { default as IconMacOs } from "./mac-os.svg"
export { default as IconWindowOs } from "./window-os.svg"
export { default as IconFirefox } from "./firefox.svg"
export { default as IconChrome } from "./chrome.svg"
export { default as IconFilter } from "./filter.svg"
export { default as groupIcons } from "./groupIcons.svg"
export { default as IconCreateTeam } from "./create-team.svg"
export { default as IconJoinTeam } from "./join-team.svg"
