export { default as IconFilter } from './Icon-filter.svg'
export { default as IconRecover } from './Icon-recover.svg'
export { default as IconReTrash } from './Icon-retrash.svg'
export { default as IconRefreshSquare } from './Refresh Square.svg'
export { default as IconEmptyFolder } from './empty-folder.vue'