export { default as BrowsersChromeIcon} from "./Browsers.svg"
export { default as BrowsersFoxIcon} from "./Browsers (1).vue"
export { default as CheckBeadIcon} from "./Check Read.svg"
export { default as ContentUploadIcon} from "./Content upload 1.vue"
export { default as EditIcon} from "./edit.svg"
export { default as EmptyInboxIcon} from "./Empty Inbox 1.vue"
export { default as LoginIcon} from "./Login 5.svg"
export { default as PaintRollerIcon} from "./Paint Roller.svg"
export { default as QRCodeIcon} from "./QR Code.svg"
export { default as RefreshIcon} from "./Refresh.svg"
export { default as WidgetIcon} from "./Widget 18.svg"
export { default as WrapperIcon } from "./Icon-Wrapper.svg"
export { default as LogoutBlackIcon } from "./logout-black.svg"